image: python:3.8-slim

pages:
  script:
  - pip install -r requirements.txt
  - pytest ./tests/
  - apt-get update
  - apt-get upgrade -y
  - apt-get install build-essential -y
  - cd ./docs
  - make html
  - cd ..
  - mv ./docs/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master
