image: python:3.8-slim

pages:
  script:
  - pip install -r requirements.txt
  - cd ./docs
  - make html
  - cd ..
  - mv ./docs/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master
