'''
Functions for merging Sentinel-2 derived multi-band geoTiff files
generated by ``agrisatpy.spatial_resampling.sentinel2.resample_and_stack_s2``.

Merging can become necessary to combine image files from two different
datatakes over the same scenery (same location and image acquisition time).
'''

from pathlib import Path
from typing import List


def merge_s2_safe_archives(
        safe_archives: List[Path]
    ):
    """
    Takes a list of S2 datasets in .SAFE format and merges them into a single
    multi-band geoTiff file using ``agrisatpy.spatial_resampling.sentinel2.resample_and_stack_s2``
    for generating a geoTiff for each .SAFE dataset. These geoTiffs are then merged
    in a second step into a single one. In addition, the function takes care about the
    TCI RGB preview and (if available) the scene classification layer.

    :param safe_archives:
        list of .SAFE datasets to merge.
    """
    pass
    