version: "3.9"

services:
  db:
    image: "postgres:13.4"
    env_file:
      - .env
    container_name: agrisatpy_metadb
    build:
      context: ../
      dockerfile: docker-services/Dockerfiles/metadb-setup.dockerfile
    volumes:
      - agrisatpy-metadb:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  agrisatpy-metadb:
